[project]
name = "agentcore"
version = "0.1.0"
description = "Prototype core agent"
readme = "README.md"
requires-python = ">=3.11"

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
